--[[
    Pour / mix / garnish recipes for the bar.
]]

BarConfig = BarConfig or {}
BarConfig.Recipes = {
    {
        id = 'pour_spirit_to_glass',
        label = 'Pour',
        interaction = 'pour',
        sourceItems = { 'whisky', 'vodka', 'rum' },
        sourceCategories = { 'drink' },
        targetItems = { 'glass' },
        targetCategories = { 'glassware' },
        consumeSource = 40,
        addToTarget = { amountDelta = 40, setIce = false },
        animation = 'pour',
        duration = 2200,
    },
    {
        id = 'pour_mixer_to_glass',
        label = 'Pour Mixer',
        interaction = 'pour',
        sourceItems = { 'coke', 'tonic' },
        sourceCategories = { 'mixer' },
        targetItems = { 'glass' },
        targetCategories = { 'glassware' },
        consumeSource = 60,
        addToTarget = { amountDelta = 60 },
        animation = 'pour',
        duration = 1800,
    },
    {
        id = 'add_ice_to_glass',
        label = 'Add Ice',
        interaction = 'add_ice',
        sourceItems = { 'ice' },
        targetItems = { 'glass' },
        targetCategories = { 'glassware' },
        consumeSource = 1,
        consumeCarry = true,
        addToTarget = { ice = true },
        animation = 'use',
        duration = 1200,
    },
    {
        id = 'add_lemon_to_glass',
        label = 'Add Garnish',
        interaction = 'add_garnish',
        sourceItems = { 'lemon' },
        targetItems = { 'glass' },
        targetCategories = { 'glassware' },
        consumeSource = 1,
        consumeCarry = true,
        addToTarget = { garnish = 'lemon' },
        animation = 'use',
        duration = 1200,
    },
    {
        id = 'whisky_coke_mix',
        label = 'Mix Whisky Coke',
        interaction = 'mix',
        sourceItems = { 'coke' },
        targetItems = { 'glass' },
        requireTargetState = { liquid = 'whisky' },
        consumeSource = 80,
        addToTarget = {
            liquid = 'whisky_coke',
            amountDelta = 80,
        },
        animation = 'pour',
        duration = 2000,
    },
    {
        id = 'vodka_tonic_mix',
        label = 'Mix Vodka Tonic',
        interaction = 'mix',
        sourceItems = { 'tonic' },
        targetItems = { 'glass' },
        requireTargetState = { liquid = 'vodka' },
        consumeSource = 80,
        addToTarget = {
            liquid = 'vodka_tonic',
            amountDelta = 80,
        },
        animation = 'pour',
        duration = 2000,
    },
}
